name: 'Set Google Cloud Datastore Entity'
description: 'Insert or update an entity in Google Cloud Datastore'
inputs:
  credentials:
    description: 'Service account key encoded in base64.'
    required: true
  project_id:
    description: 'Google Cloud project ID'
    required: true
  action:
    description: 'Action to perform on the entity. "save" will overwrite the whole entity, while "merge" will keep the existing value that are not specified.'
    required: true
    default: save
  entity_kind:
    description: 'Kind of entity'
    required: true
  entity_name:
    description: 'Name of the entity to insert/update'
    required: true
  entity_data:
    description: 'JSON representation of the entity data'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'database'
  color: 'blue'
